### ISSUE TITLE
Order wrong for routes on Gandalf Main

### ISSUE THREAD

**Issue by ryecroft** [rockfax/rockfax-digital-package-issues#14]
Hi,

I'd thought I should let you know that two of the routes on Gandalf Main in Lofoten Rock are wrong/should be swapped. Gollum nr 14 and Smeagol nr 15.

It even says so in the description of the routes. 
Gollum: "...a few meters to the left of Gandalf"
Smeagol: "Plugs the gap between Gollum and Lost Gandalf with..."

But now the app shows in this order: 
Lost Gandalf - Gollum - Smeagol - Gandalf.

Best regards from a climber native from Lofoten,

Andreas

**Comment by alanjamesrockfax** [comment]
Corrected in the master version.
