### ISSUE TITLE
Double topo line select: Tenerife - Los Naranjos

### ISSUE THREAD

**Issue by JohnMcKenna1992** [rockfax/rockfax-digital-package-issues#27]
Some routes in Los Naranjos in Tenerife when clicked on are selecting two route lines on the topo. 24-28 and 26-29
Or if selecting 28 or 29 from descriptions - then only start point selected in topo view

**Comment by alanjamesrockfax** [comment]
Now corrected in the master document. There were wrong route numbers perfectly positioned under the top ones which was linking the route line to the wrong route.
