### ISSUE TITLE
Millstone, North Bay - Routes in incorrect position on topo

### ISSUE THREAD

**Issue by mkmckenna** [rockfax/rockfax-digital-package-issues#33]
**Describe the error**
A clear and concise description of what the error is.

Photo is out of sync with the correct route locations. Everything seems to have shifted left.

Please fill in any of the following that are relevant:
**Book/Area**

**Crag**

Millstone

**Buttress**

North Bay

**Route**

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Additional context**

Reported by user via email on 27/08/2022 - charliestephenson1974@gmail.com

**Comment by alanjamesrockfax** [comment]
Corrected

**Comment by alanjamesrockfax** [comment]
Corrected
